version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - mynet
    restart: unless-stopped

  minio:
    container_name: minio_container
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    networks:
      - mynet
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: secretpassword
    command: server --console-address ":9001" /data

networks:
  mynet:
    driver: bridge

volumes:
  postgres:
  minio_storage: